### ISSUE TITLE
link to installer is broken

### ISSUE THREAD

**Issue by sloredo214** [coatless/r-macos-clang#11]
Hi, 
I am trying to open the following link [https://uofi.box.com/v/r-macos-clang-pkg] but it leads to a blank empty page.

Thanks, 
Stephanie

**Comment by coatless** [comment]
I can't replicate this. Are you clicking on:

https://uofi.box.com/v/r-macos-clang-pkg

If so, you should see:

<img width="1071" alt="screen shot 2017-12-07 at 9 46 49 pm" src="https://user-images.githubusercontent.com/833642/33750259-3a5a85d8-db98-11e7-8307-6295d44a80b7.png">

**Comment by coatless** [comment]
I'm going to close this issue since:

1. I haven't been able to reproduce the error and,
2. There has been no follow up by the reporting party.
